### PR TITLE
Moisture boards txt

### PR DESCRIPTION
**Pull request by andershedberg**

### CODE REVIEW

**Comment by andershedberg** [comment]
Not to be merged by original repository.

**Comment by vicatcu** [comment]
@andershedberg I haven't been following closely for a while, and not to take take anything away from @maniacbug, but I think this core / repo is way out of date. It supplies its own copy of the Arduino core that is way out of date with the state of the art standard core (e.g. things like malloc and string). My WildFire board basically just uses the standard arduino core with Optiboot and my own pin mappings via pins_arduino.h. It's on github here if you want to have a look at an alternative https://github.com/wickeddevice/wildfire-Arduino-Core

**Comment by vicatcu** [comment]
... also includes the latest Optiboot that works with the 1284p

**Comment by andershedberg** [comment]
Thanks, I errored and thought I did a merge to my own fork on github (which
I use as a git subproject). Sorry for that. It should not be merged to your
repo. I'll look at the wildfire stuff! /Anders H.

On Fri, Jan 30, 2015 at 5:45 PM, Victor Aprea notifications@github.com
wrote:

> ... also includes the latest Optiboot that works with the 1284p
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maniacbug/mighty-1284p/pull/13#issuecomment-72230654.

## 

Anders Hedberg,
mobile +46 733 320 196

**Pull request closed without merging**
